plugins:
  ldap_enabled:
    default: true
  ldap_user_create_mode:
    default: 'auto'
  ldap_hostname:
    default: 'adfs.example.com'
  ldap_port:
    default: 389
  ldap_method:
    default: 'plain'
  ldap_base:
    default: 'dc=example,dc=com'
  ldap_uid:
    default: 'sAMAccountName'
  ldap_bind_dn:
    default: ''
  ldap_password:
    default: ''
  ldap_filter:
    default: ''
